name: dicume_app
description: "App educacional nutricional para pessoas com diabetes tipo 2 em Imperatriz-MA"

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  # Core Dependencies
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  # Local Database & Cache
  drift: ^2.20.3
  sqlite3_flutter_libs: ^0.5.24
  path_provider: ^2.1.1
  path: ^1.8.3

  # HTTP & Network
  dio: ^5.4.0
  pretty_dio_logger: ^1.3.1
  connectivity_plus: ^6.1.4
  # Authentication & Security
  google_sign_in: ^6.2.1
  flutter_secure_storage: ^10.0.0-beta.4
  jwt_decoder: ^2.0.1

  # UI & Animations
  lottie: ^3.3.1
  flutter_animate: ^4.3.0
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  go_router: ^15.2.0

  # Feedback Tátil e Sonoro
  vibration: ^2.0.0
  audioplayers: ^6.1.0

  # Utils
  intl: ^0.20.2
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  dartz: ^0.10.1

  # Fonts
  google_fonts: ^6.1.0

  # Icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generation
  riverpod_generator: ^2.3.9
  build_runner: ^2.4.7
  drift_dev: ^2.20.1
  json_serializable: ^6.7.1

  # Testing
  mockito: ^5.4.4

  # Linting
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  # Assets
  assets:
    - assets/images/
    - assets/animations/
    - assets/lottie/

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
